moved main to bottom

diff --git a/bin/cosmic-log b/bin/cosmic-log
--- a/bin/cosmic-log
+++ b/bin/cosmic-log
@@ -3,21 +3,6 @@
 # TODO: create new messages for ship using templates
 # TODO: better isolate listings.gophermap from accidental clobbering
 
-version="0.1.0"
-user=$(whoami)
-ships=$(find /var/gopher -user "$user" -type d -exec basename {} \;)
-numships=$(echo "${ships}" | wc -l)
-tmp=$(mktemp -t "$(basename "$0").tmp.XXXXXXX") || die "Failed to create temporary file" 1
-
-flag_help=0
-flag_version=0
-flag_debug=0
-flag_shortlist=0
-
-arg_options="hvds:z"
-arg_log=1
-arg_ship=""
-
 die () {
   msg="$1"
   code="$2"
@@ -42,7 +27,7 @@ finish () {
 trap finish EXIT
 
 parse_input () {
-  if ! parsed=$(getopt $arg_options "$@"); then
+  if ! parsed=$(getopt "$arg_options" "$@"); then
     die "Invalid input" 2
   fi
 
@@ -197,5 +182,24 @@ main() {
     fi
   fi
 }
+
+##############################################################################
+##############################################################################
+##############################################################################
+
+version="0.1.0"
+user=$(whoami)
+ships=$(find /var/gopher -user "$user" -type d -exec basename {} \;)
+numships=$(echo "${ships}" | wc -l)
+tmp=$(mktemp -t "$(basename "$0").tmp.XXXXXXX") || die "Failed to create temporary file" 1
+
+flag_help=0
+flag_version=0
+flag_debug=0
+flag_shortlist=0
+
+arg_options="hvds:z"
+arg_log=1
+arg_ship=""
 
 main "$@"
