publish manages log

diff --git a/bin/log b/bin/log
--- a/bin/log
+++ b/bin/log
@@ -1,7 +1,5 @@
 #!/bin/sh
 
-# TODO: better isolate listings.gophermap from accidental clobbering
-
 YELLOW="$(tput setaf 11)"
 GREEN="$(tput setaf 10)"
 RED="$(tput setaf 9)"
@@ -173,6 +171,22 @@ new_message () {
 }
 
 main() {
+  version="0.1.0"
+  user="$SUDO_USER"
+  ships=$(find /var/gopher -user "$user" -type d -exec basename {} \;)
+  numships=$(echo "${ships}" | wc -l)
+  tmp=$(mktemp -t "$(basename "$0").tmp.XXXXXXX") || die "Failed to create temporary file" 1
+
+  flag_help=0
+  flag_version=0
+  flag_debug=0
+  flag_shortlist=0
+
+  arg_options="hvds:zn:"
+  arg_log=1
+  arg_ship=""
+  arg_new=""
+
   parse_input "$@"
 
   # debug
@@ -245,20 +259,9 @@ main() {
 ##############################################################################
 ##############################################################################
 
-version="0.1.0"
-user=$(whoami)
-ships=$(find /var/gopher -user "$user" -type d -exec basename {} \;)
-numships=$(echo "${ships}" | wc -l)
-tmp=$(mktemp -t "$(basename "$0").tmp.XXXXXXX") || die "Failed to create temporary file" 1
-
-flag_help=0
-flag_version=0
-flag_debug=0
-flag_shortlist=0
-
-arg_options="hvds:zn:"
-arg_log=1
-arg_ship=""
-arg_new=""
-
-main "$@"
+run_user=$(id -u)
+if [ "$run_user" -eq 0 ] || [ "$run_user" -eq 1038 ]; then
+  main "$@"
+else
+  exec sudo -u publish "$0" "$@"
+fi
